do not test result order
Teamwork/sharedb-mingo-memory pull request #1
Opened 2018-06-28 05:51 UTC by dcharbonnier

The order of the results does not matter on those cases and tests are randomly failing on sharedb-mongo due to this problem

2018-07-02 12:57 UTC, curran requested changes
The idea and implementation looks good, but there is a minor formatting issue where 3 spaces are used as indentation.

2018-07-02 12:57 UTC, curran commented on test/query.js
> +   return snapshots.sort(function (a, b) {
Inconsistent indentation here.

2018-07-02 13:08 UTC, curran approved these changes
Looks good to me!

2018-07-09 16:05 UTC, merged

2018-07-09 16:06 UTC, gkubisa commented
Nice one! Thanks @dcharbonnier and @curran

2018-07-09 17:20 UTC, curran commented
Hooray!